/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PokerRouteImport } from './routes/poker'
import { Route as PiciniRouteImport } from './routes/picini'
import { Route as NacheinanderRouteImport } from './routes/nacheinander'
import { Route as ImposterRouteImport } from './routes/imposter'
import { Route as Fragen99RouteImport } from './routes/fragen99'
import { Route as DuemmsterRouteImport } from './routes/duemmster'
import { Route as IndexRouteImport } from './routes/index'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PokerRoute = PokerRouteImport.update({
  id: '/poker',
  path: '/poker',
  getParentRoute: () => rootRouteImport,
} as any)
const PiciniRoute = PiciniRouteImport.update({
  id: '/picini',
  path: '/picini',
  getParentRoute: () => rootRouteImport,
} as any)
const NacheinanderRoute = NacheinanderRouteImport.update({
  id: '/nacheinander',
  path: '/nacheinander',
  getParentRoute: () => rootRouteImport,
} as any)
const ImposterRoute = ImposterRouteImport.update({
  id: '/imposter',
  path: '/imposter',
  getParentRoute: () => rootRouteImport,
} as any)
const Fragen99Route = Fragen99RouteImport.update({
  id: '/fragen99',
  path: '/fragen99',
  getParentRoute: () => rootRouteImport,
} as any)
const DuemmsterRoute = DuemmsterRouteImport.update({
  id: '/duemmster',
  path: '/duemmster',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duemmster': typeof DuemmsterRoute
  '/fragen99': typeof Fragen99Route
  '/imposter': typeof ImposterRoute
  '/nacheinander': typeof NacheinanderRoute
  '/picini': typeof PiciniRoute
  '/poker': typeof PokerRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/duemmster': typeof DuemmsterRoute
  '/fragen99': typeof Fragen99Route
  '/imposter': typeof ImposterRoute
  '/nacheinander': typeof NacheinanderRoute
  '/picini': typeof PiciniRoute
  '/poker': typeof PokerRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duemmster': typeof DuemmsterRoute
  '/fragen99': typeof Fragen99Route
  '/imposter': typeof ImposterRoute
  '/nacheinander': typeof NacheinanderRoute
  '/picini': typeof PiciniRoute
  '/poker': typeof PokerRoute
  '/quiz': typeof QuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/duemmster'
    | '/fragen99'
    | '/imposter'
    | '/nacheinander'
    | '/picini'
    | '/poker'
    | '/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/duemmster'
    | '/fragen99'
    | '/imposter'
    | '/nacheinander'
    | '/picini'
    | '/poker'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/duemmster'
    | '/fragen99'
    | '/imposter'
    | '/nacheinander'
    | '/picini'
    | '/poker'
    | '/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuemmsterRoute: typeof DuemmsterRoute
  Fragen99Route: typeof Fragen99Route
  ImposterRoute: typeof ImposterRoute
  NacheinanderRoute: typeof NacheinanderRoute
  PiciniRoute: typeof PiciniRoute
  PokerRoute: typeof PokerRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poker': {
      id: '/poker'
      path: '/poker'
      fullPath: '/poker'
      preLoaderRoute: typeof PokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picini': {
      id: '/picini'
      path: '/picini'
      fullPath: '/picini'
      preLoaderRoute: typeof PiciniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nacheinander': {
      id: '/nacheinander'
      path: '/nacheinander'
      fullPath: '/nacheinander'
      preLoaderRoute: typeof NacheinanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imposter': {
      id: '/imposter'
      path: '/imposter'
      fullPath: '/imposter'
      preLoaderRoute: typeof ImposterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragen99': {
      id: '/fragen99'
      path: '/fragen99'
      fullPath: '/fragen99'
      preLoaderRoute: typeof Fragen99RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duemmster': {
      id: '/duemmster'
      path: '/duemmster'
      fullPath: '/duemmster'
      preLoaderRoute: typeof DuemmsterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuemmsterRoute: DuemmsterRoute,
  Fragen99Route: Fragen99Route,
  ImposterRoute: ImposterRoute,
  NacheinanderRoute: NacheinanderRoute,
  PiciniRoute: PiciniRoute,
  PokerRoute: PokerRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
