// 99 Fragen – "Wer würde am ehesten...?" Spielmodus.
// Spieler liest Karte vor und gibt das Handy an die Person weiter,
// zu der die Frage am besten passt. Diese Person trinkt und liest die nächste Karte.
export type Fragen99Category = "klassisch" | "action" | "hotspicy";

export const FRAGEN99_CATEGORIES: {
  id: Fragen99Category;
  label: string;
  emoji: string;
  desc: string;
}[] = [
  { id: "klassisch", label: "Klassisch", emoji: "💬", desc: "Persönlich, ehrlich, harmlos" },
  { id: "action", label: "Action", emoji: "⚡", desc: "Bewegt, mutig & ein bisschen verrückt" },
  { id: "hotspicy", label: "Hot & Spicy", emoji: "🌶️", desc: "Pikant, ab 18 – flirty & frech" },
];

export const FRAGEN99_LIMIT = 99;

export const FRAGEN99_QUESTIONS: Record<Fragen99Category, string[]> = {
  klassisch: [
    "Wer würde am ehesten heimlich Reality-TV im Bett schauen?",
    "Wer macht im Urlaub die meisten Selfies?",
    "Wer würde am ehesten 2 Stunden zu spät zur eigenen Hochzeit kommen?",
    "Wer in der Runde hat das chaotischste Zimmer?",
    "Wer würde am ehesten in eine Sekte geraten?",
    "Wer könnte am längsten ohne Internet überleben?",
    "Wer würde einen Promi treffen und ihn nicht erkennen?",
    "Wer hat hier das absurdeste Spotify-Hörverhalten?",
    "Wer würde am ehesten ohne Plan einfach auswandern?",
    "Wer checkt mindestens 50× am Tag sein Handy?",
    "Wer würde am ehesten ein Hotel-Personal mit dem Vornamen ansprechen, ohne zu fragen?",
    "Wer würde sich am wenigsten an ein Versprechen erinnern, das vor zwei Bier abgegeben wurde?",
    "Wer würde am ehesten beim Date 1 Stunde zu früh da sein?",
    "Wer hat hier den schlechtesten Geschmack bei Filmen?",
    "Wer würde am ehesten in seinem Auto schlafen, statt nach Hause zu fahren?",
    "Wer hat in der Runde das peinlichste Schulfoto?",
    "Wer würde mit 70 noch in Clubs gehen?",
    "Wer würde am ehesten einen TikTok-Trend starten und es nicht mal merken?",
    "Wer kauft sich Dinge online, die er drei Wochen später bereut?",
    "Wer würde am ehesten ein Haustier kaufen, ohne es vorher abzustimmen?",
    "Wer ist hier morgens am unzurechnungsfähigsten?",
    "Wer würde am ehesten beim Lügen rot werden?",
    "Wer hat die meisten alten Schulfreunde komplett aus den Augen verloren?",
    "Wer würde am ehesten in einer Quiz-Show in der ersten Frage rausfliegen?",
    "Wer ist im Freundeskreis die wandelnde Wikipedia für Klatsch?",
    "Wer würde am ehesten heimlich an einem WG-Putzplan rütteln?",
    "Wer ist hier am unwahrscheinlichsten pünktlich?",
    "Wer würde am ehesten von Beruf YouTuber sein können?",
    "Wer wird am ehesten 100 Jahre alt – und warum?",
    "Wer hat in seiner Handy-Galerie aktuell die peinlichsten Screenshots?",
    "Wer würde am ehesten Karaoke ohne Alkohol singen?",
    "Wer in der Runde ist heimlich am organisiertesten?",
    "Wer hat hier die größte Sammlung von etwas Komischem?",
    "Wer würde am ehesten einen Aprilscherz nicht erkennen?",
    "Wer würde am ehesten beim Möbel-Aufbauen die Anleitung wegwerfen?",
    "Wer hat hier den absurdesten Lieblingsfilm aus der Kindheit?",
    "Wer würde am ehesten eine Stunde lang über Pizza-Beläge diskutieren?",
    "Wer würde am ehesten heimlich auf einer Beerdigung lachen?",
    "Wer hat hier am ehesten ein selbstgemaltes Bild von sich an der Wand?",
    "Wer würde am ehesten Eltern werden, ohne sich darauf vorzubereiten?",
    "Wer hat das längste 'Eines Tages mache ich…'-To-do auf seiner Liste?",
    "Wer würde am ehesten als 'eigenartig, aber liebenswert' beschrieben werden?",
    "Wer würde am ehesten beim Tee-Trinken den kleinen Finger heben?",
    "Wer hat im Freundeskreis die nervigste Lachstimme?",
    "Wer würde am ehesten heimlich seinen Wecker fünfmal hintereinander snoozen?",
    "Wer hat hier die merkwürdigste Geheimangst?",
    "Wer würde am ehesten 'Ich kann das auch selbst' sagen – und scheitern?",
    "Wer hat hier das chaotischste Handy-Display voller Apps?",
    "Wer würde am ehesten beim Spielabend richtig sauer werden?",
    "Wer hat das peinlichste Geräusch beim Essen?",
    "Wer ist am ehesten der/die, der/die alle Geheimnisse für sich behält?",
    "Wer ist hier am ehesten ein wandelnder Wikipedia-Fakten-Crash?",
    "Wer würde am ehesten in einer Mittagspause einschlafen?",
    "Wer würde am ehesten den/die Briefträger:in mit Vornamen kennen?",
    "Wer hat hier den meisten heimlichen Konsum von Schnulzen-Filmen?",
    "Wer würde am ehesten auf den eigenen Geburtstag vergessen?",
    "Wer hat hier den unglücklichsten WG-Mitbewohner gewählt?",
    "Wer würde am ehesten in einer Apokalypse zuerst gefressen werden?",
    "Wer ist am wahrscheinlichsten der/die, der/die im Krimi-Buch zuerst stirbt?",
    "Wer würde am ehesten heimlich Pflanzennamen falsch aussprechen?",
    "Wer ist heimlich am meisten Schoko-süchtig?",
    "Wer würde am ehesten in der Sauna laut quatschen?",
    "Wer hat hier den nervigsten Lachausbruch beim Komiker-Stand-up?",
    "Wer würde am ehesten beim Spinning-Kurs umkippen?",
    "Wer würde am ehesten nach 3 Stunden Yoga aufgeben?",
    "Wer hat hier die längste Liste an 'Ungelesen' auf WhatsApp?",
    "Wer würde am ehesten auf dem Klo einschlafen?",
    "Wer ist hier am süßesten beim Frühstück?",
    "Wer würde am ehesten beim Brettspiel cheaten?",
    "Wer hat hier die schrägste Sammlung an Tassen?",
    "Wer hat hier das peinlichste 'Liebes-SMS-Verlauf'-Archiv?",
    "Wer würde am ehesten eine Geheimkollege/in-Schwärmerei in der Arbeit haben?",
    "Wer würde am ehesten beim Quiz-Abend die Antwort schreien, bevor jemand fragt?",
    "Wer ist hier die größte 'Was-koche-ich-heute?'-Krise?",
    "Wer hat hier am ehesten ein Hobby, das niemand versteht?",
    "Wer würde am ehesten heimlich Schokoladen-Riegel im Schrank verstecken?",
    "Wer in der Runde ist am ehesten heimlich Maximalist im Kleiderschrank?",
    "Wer ist am ehesten ein heimlicher Fan von schlechtem Trash-TV?",
    "Wer würde am ehesten in einer Diskussion 'Schau in den Spiegel!' sagen?",
    "Wer hat hier den größten Sneaker- oder Schuhwahn?",
    "Wer würde am ehesten 4 Stunden lang nach einem Parkplatz suchen?",
    "Wer hat hier den lautesten Husten?",
    "Wer würde am ehesten heimlich ein zweites Frühstück bei der Arbeit haben?",
    "Wer in der Runde war als Kind am unausstehlichsten?",
    "Wer würde am ehesten eine ganze Nacht durchquatschen, ohne müde zu werden?",
    "Wer würde am ehesten Vegan werden – nur um es Instagram-fähig zu posten?",
    "Wer hat hier am ehesten einen heimlichen Beauty-Geheim-Trick?",
    "Wer würde am ehesten als Influencer:in für Fußpilz-Salbe werben?",
    "Wer ist hier am ehesten der Schul-Ex-Schwarm geworden?",
    "Wer würde am ehesten als Erste/r aus dem Bus springen, wenn jemand pupst?",
    "Wer hat hier am ehesten eine bizarre Schlafgewohnheit?",
    "Wer würde am ehesten 'Ich bin so beschäftigt' sagen, ist es aber gar nicht?",
    "Wer in der Runde hat die merkwürdigsten Wachträume?",
    "Wer hat hier den verspätetsten Schulabschluss?",
    "Wer würde am ehesten beim Wandern fünfmal die falsche Abzweigung nehmen?",
    "Wer in der Runde hört Musik, die niemand kennt?",
    "Wer würde am ehesten heimlich einen Roman schreiben?",
    "Wer hat hier das absurdeste 'Geheim-Hobby'?",
    "Wer würde am ehesten beim Frühlingsputz drei Tage lang in alten Fotos versinken?",
    "Wer hat hier am ehesten eine geheime Star Wars/Marvel-Phase?",
    "Wer würde am ehesten beim Friseur 'wie immer' sagen und dann unzufrieden sein?",
    "Wer ist hier am ehesten der heimliche Drama-Magnet?",
    "Wer hat hier am ehesten eine private Notiz-App voller verrückter Ideen?",
    "Wer würde am ehesten beim Brunch zu viel bestellen?",
    "Wer in der Runde ist am ehesten Sonntagstrinker statt Wochenende-Krieger?",
    "Wer hat hier am ehesten unausgepackte Pakete von vor 6 Monaten?",
    "Wer würde am ehesten beim Wichteln das billigste Geschenk machen?",
    "Wer würde am ehesten 'Ich hab das schon mal in Asien gegessen' sagen?",
    "Wer würde am ehesten ein 'Ich-trinke-keinen-Alkohol-mehr'-Projekt starten und scheitern?",
    "Wer ist hier am ehesten die größte Sushi-Liebe?",
    "Wer würde am ehesten beim Date über die Kindheit reden?",
    "Wer hat hier die längste Liste an 'Filme, die ich noch schauen will'?",
    "Wer würde am ehesten beim Frühstück über das Mittagessen entscheiden?",
    "Wer ist hier am ehesten der/die Sterneköch:in der Runde?",
    "Wer würde am ehesten ein Buch nach 30 Seiten abbrechen?",
    "Wer ist hier am ehesten heimlich religiös?",
    "Wer würde am ehesten Astrologie ernst nehmen, ohne es zuzugeben?",
    "Wer in der Runde ist am ehesten ein/e geborene/r Krisenmanager:in?",
    "Wer hat hier am ehesten ein 'Ich-würde-im-Vergleich-zu-anderen…'-Komplex?",
    "Wer würde am ehesten heimlich auf eine Buchpräsentation gehen?",
    "Wer in der Runde ist am ehesten ein Morgenmensch, der nie zugibt, dass er müde ist?",
    "Wer hat hier am ehesten ein heimliches Lieblings-Café?",
    "Wer würde am ehesten 'das ist Kunst' zu etwas sagen, was kein Mensch versteht?",
    "Wer hat hier am ehesten eine Sammlung Receipts (Quittungen) wie ein 90er-Jahre-Buchhalter?",
    "Wer würde am ehesten heimlich Cider statt Bier bevorzugen?",
    "Wer würde am ehesten beim Wandern mit zu wenig Wasser starten?",
    "Wer in der Runde ist am ehesten der/die Heizungs-Boss?",
    "Wer hat hier die abenteuerlichste Bestellgewohnheit beim Lieferdienst?",
    "Wer würde am ehesten heimlich eine Pflanze sterben lassen?",
    "Wer hat hier am ehesten das chaotischste Auto?",
    "Wer würde am ehesten in einer Tankstellen-Schlange ungeduldig werden?",
    "Wer würde am ehesten 5 Minuten zu früh zu Bett gehen, weil 'gleich startet die Serie'?",
    "Wer hat hier am ehesten den schräcksten Schlafsong?",
    "Wer würde am ehesten beim Putzen 4 Songs verlieren in der Musik?",
    "Wer ist hier am ehesten heimlich abergläubisch?",
    "Wer würde am ehesten beim Sushi-Essen alles in Sojasauce ertränken?",
    "Wer hat hier am ehesten einen Lieblings-Wikipedia-Artikel?",
    "Wer würde am ehesten beim Wandern Schmerzen 'wegatmen'?",
    "Wer in der Runde ist am ehesten ein/e heimlicher Pilates-Fanatiker:in?",
    "Wer würde am ehesten ein Geschenk wieder mitnehmen, weil es 'zu viel' war?",
    "Wer hat hier am ehesten eine geheime Hass-Liebe gegen einen Promi?",
    "Wer würde am ehesten eine Tasse so lange auf dem Schreibtisch lassen, bis sie Schimmel ansetzt?",
    "Wer in der Runde ist am ehesten der/die Schoko-Hamster:in?",
    "Wer würde am ehesten beim Friseur 'das ist genug' sagen, obwohl es nicht genug ist?",
    "Wer hat hier am ehesten eine heimliche Genussroutine am Sonntag?",
    "Wer würde am ehesten beim Spaziergang Stöckchen aufsammeln?",
    "Wer in der Runde ist am ehesten der/die heimliche Influencer:in-für-Nachbarn?",
    "Wer würde am ehesten beim Online-Shopping 'kostenloser Versand' triggern, indem er noch was dazukauft?",
    "Wer hat hier am ehesten die meisten 'Begonnen, nie beendet'-Hobbys?",
    "Wer würde am ehesten in einer Diskussion bei 'Wikipedia sagt…' anfangen?",
    "Wer hat hier am ehesten das längste Spotify-Wrapped des Jahres?",
    "Wer würde am ehesten beim Kochen die Hälfte der Zutaten vergessen?",
    "Wer in der Runde ist am ehesten ein Snack-Geheim-Sammler?",
    "Wer würde am ehesten Tinder löschen und neu installieren – wöchentlich?",
    "Wer hat hier am ehesten den lautesten Niesreflex?",
    "Wer würde am ehesten beim Streiten gleich 'ich bin nicht sauer' sagen?",
    "Wer hat hier am ehesten eine Wohnung mit unnötig vielen Kissen?",
    "Wer würde am ehesten heimlich beim Einkaufen Süßigkeiten essen, vor dem Bezahlen?",
    "Wer in der Runde ist am ehesten heimlich ein Stammgast in einem Café?",
    "Wer würde am ehesten beim Brunch fünf verschiedene Sorten Marmelade probieren wollen?",
    "Wer hat hier am ehesten ein 'Spar-Kühlschrank-Tetris' am Laufen?",
    "Wer würde am ehesten ihn-/sie-selbst auf Insta unfollowen, einfach so?",
    "Wer ist hier am ehesten der/die 'Schoki im Gefrierfach'-Hortmensch?",
    "Wer würde am ehesten in der Bibliothek einschlafen?",
    "Wer hat hier am ehesten am wenigsten Geduld in der Schlange beim Bäcker?",
    "Wer würde am ehesten beim Date Verstopfung als Smalltalk-Thema nutzen?",
    "Wer in der Runde ist heimlich am politischsten?",
    "Wer würde am ehesten in einem Aldi-Mittwoch-Angebot zuschnappen, ohne es zu brauchen?",
    "Wer hat hier am ehesten das beste 'Was-passiert-wenn'-Gedanken-Karussell?",
    "Wer würde am ehesten beim Spazierengehen Pflanzen-Apps benutzen?",
    "Wer in der Runde ist am ehesten der/die 'Ich-trinke-grünen-Tee'-Mensch?",
    "Wer würde am ehesten heimlich Strick-Tutorials schauen?",
    "Wer hat hier am ehesten eine bunte Sticker-Sammlung am Laptop?",
    "Wer würde am ehesten Wein im Glas schwenken, ohne den Grund zu kennen?",
    "Wer in der Runde ist am ehesten ein/e heimliche/r Krimi-Podcast-Jünger:in?",
    "Wer würde am ehesten beim Wandern Tipps geben, ohne gefragt zu werden?",
    "Wer hat hier am ehesten Sneaker, die mehr kosten als die Miete?",
    "Wer würde am ehesten beim Spielabend strategisch Allianzen schmieden?",
    "Wer hat hier am ehesten eine geheime Lieblings-Anime-Serie?",
    "Wer würde am ehesten 'Das musst du sehen' sagen und es zwei Mal vergessen zu schicken?",
    "Wer in der Runde ist am ehesten der/die Stress-Bäcker:in?",
    "Wer würde am ehesten ein Buch nur wegen des Covers kaufen?",
    "Wer hat hier am ehesten eine WhatsApp-Gruppe nur mit sich selbst?",
    "Wer würde am ehesten heimlich Liedtexte mit der falschen Aussprache singen?",
    "Wer hat hier den merkwürdigsten Gemüse-Vorrat-Hang?",
    "Wer würde am ehesten beim Brunch 'einen Kaffee dazu' bestellen und vergessen, ihn zu trinken?",
    "Wer ist hier am ehesten der/die heimliche Newsletter-Anhäufer:in?",
    "Wer würde am ehesten Spam-Anrufe annehmen, weil es 'Spaß macht'?",
    "Wer hat hier am ehesten Lieblings-Geheim-Bingewatching-Lust?",
    "Wer würde am ehesten beim Geschenk-Aussuchen alles kaufen wollen?",
    "Wer in der Runde ist am ehesten der/die 'Verschwende-keine-Sekunde'-Typ?",
    "Wer würde am ehesten heimlich Kindergeburtstag mögen?",
    "Wer hat hier am ehesten eine sortierte Gewürz-Schublade?",
    "Wer würde am ehesten als Erste/r ein eigenes Café eröffnen?",
    "Wer hat hier am ehesten 'Ich mag das gar nicht'-Phrasen für Essen, das er nie probiert hat?",
    "Wer würde am ehesten heimlich Sudoku lieben?",
    "Wer in der Runde ist am ehesten der/die Plan-Veränderer der letzten Minute?",
    "Wer würde am ehesten als Letzte/r am Buffet anstehen, weil er noch grübelt?",
    "Wer hat hier am ehesten heimliche Träume von einer Bühnenshow?",
    "Wer würde am ehesten heimlich eine Geheim-Lieblings-Schnulze haben?",
    "Wer ist hier am ehesten der/die Kandidat:in für eine Talkshow-Einlage?",
    "Wer würde am ehesten beim Café-Bestellen die zehnte Sonderwunsch-Phrase abfeuern?",
    "Wer hat hier am ehesten einen heimlichen Stolz auf seine Pflanzen?",
    "Wer würde am ehesten beim ersten Date über Mathematik reden?",
    "Wer in der Runde ist am ehesten heimlich Schach-Fan?",
    "Wer würde am ehesten beim Kochen zu viel 'mit der Hand schmecken'?",
    "Wer hat hier am ehesten heimlich die meisten Spotify-Playlists?",
    "Wer würde am ehesten beim Schwarz-Weiß-Foto sehnsuchtsvoll dreinblicken?",
    "Wer in der Runde ist am ehesten der/die Brunch-Master:in?",
    "Wer würde am ehesten beim Einkaufen die längste 'Eigentlich-brauche-ich-nichts'-Pause?",
    "Wer hat hier am ehesten heimlich eine Wäsche-Lieblingsmaschine?",
    "Wer würde am ehesten ein Hobby aufnehmen, das niemand sonst nachvollziehen kann?",
    "Wer ist hier am ehesten der/die 'Kann-ich-meinen-Spielzug-noch-mal-machen'-Mensch?",
    "Wer würde am ehesten in einem Buchladen mehrere Stunden bleiben?",
    "Wer hat hier am ehesten heimlich die meiste Geduld?",
  ],
  action: [
    "Wer würde am ehesten betrunken auf einen Tisch steigen und tanzen?",
    "Wer hat schon mal eine Nacht komplett durchgemacht und am nächsten Tag gearbeitet?",
    "Wer würde sich am ehesten ein Tattoo aus dem Affekt stechen lassen?",
    "Wer würde mit fremden Leuten in einen Pool springen?",
    "Wer war schon mal so betrunken, dass er den eigenen Heimweg vergessen hat?",
    "Wer würde am ehesten am Geburtstag in den falschen Club gehen und es zu spät merken?",
    "Wer hat schon mal etwas im Supermarkt geklaut – und sei es ein Bonbon?",
    "Wer würde sich am ehesten in einer Schlange ohne Grund vordrängeln?",
    "Wer hat schon mal in einem Aufzug oder Klo geschlafen?",
    "Wer würde am ehesten beim Festival in einem fremden Zelt aufwachen?",
    "Wer würde nackt im Garten campen, wenn es eine Wette wäre?",
    "Wer hat schon mal eine Polizeikontrolle erlebt, ohne dabei nüchtern zu sein?",
    "Wer würde am ehesten beim Bungee-Jumping kotzen?",
    "Wer hat schon mal heimlich aus einer fremden Bierflasche getrunken?",
    "Wer würde am ehesten eine Person ansprechen, mit der er flirtet, ohne deren Namen zu wissen?",
    "Wer hat schon mal aus Versehen ein Foto an die falsche Person geschickt?",
    "Wer würde am ehesten in einem Brunnen baden, wenn es heiß ist?",
    "Wer hat schon mal eine WhatsApp-Sprachnachricht aufgenommen, die nicht für den Empfänger gedacht war?",
    "Wer würde am ehesten beim Wandern den Weg verlieren?",
    "Wer hat schon mal in einer Bar eine Schlägerei beobachtet (oder angefangen)?",
    "Wer würde am ehesten ein Auto mieten, ohne den Führerschein dabei zu haben?",
    "Wer hat schon mal etwas getan, das er heute nüchtern niemals machen würde?",
    "Wer würde am ehesten beim Festival sein Zelt vergessen?",
    "Wer hat schon mal eine Achterbahn unfreiwillig zwei Mal hintereinander gefahren?",
    "Wer würde mit einem Fremden für einen Tag den Lebensstil tauschen?",
    "Wer hat schon mal eine ganz fremde Sprache benutzt, um Eindruck zu schinden?",
    "Wer würde am ehesten auf einer Demo aus Versehen gegen seine eigene Überzeugung mitlaufen?",
    "Wer hat schon mal eine Karaoke-Bühne gestürmt?",
    "Wer hat schon mal eine Wette so verloren, dass er sich heute noch schämt?",
    "Wer würde am ehesten in einer Disco vor allen anderen ohnmächtig werden?",
    "Wer hat schon mal das Auto seines Vaters/seiner Mutter heimlich genommen?",
    "Wer würde am ehesten beim Wandern den Rucksack vergessen?",
    "Wer hat schon mal jemanden auf einer Party geküsst, dessen Namen er nicht kannte?",
    "Wer würde am ehesten beim Wichteln das billigste Geschenk machen?",
    "Wer würde am ehesten beim Konzert die ganze Bühne stürmen wollen?",
    "Wer hat schon mal in einer fremden Wohnung übernachtet, ohne die Bewohner zu kennen?",
    "Wer würde am ehesten beim Aldi-Mittwoch im Skianzug zum Einkaufen gehen?",
    "Wer hat schon mal Pyjama im Flugzeug getragen?",
    "Wer würde am ehesten in einem fremden Garten ein Sonnenbad nehmen?",
    "Wer hat schon mal Karaoke gesungen, obwohl er nüchtern war?",
    "Wer würde am ehesten beim Marathon eine Abkürzung nehmen?",
    "Wer hat schon mal eine Toilette zerstört (versehentlich)?",
    "Wer würde am ehesten beim Wandern ein Picknick auf einer fremden Wiese machen?",
    "Wer hat schon mal Zelten in einem Park ausprobiert?",
    "Wer würde am ehesten im Flugzeug eine ganze Reihe für sich beanspruchen?",
    "Wer hat schon mal etwas verloren, das nie wieder aufgetaucht ist?",
    "Wer würde am ehesten Bungee-Jumping gehen, ohne den Anbieter zu checken?",
    "Wer hat schon mal aus einem Hotelfenster geschrien?",
    "Wer würde am ehesten beim Camping wilde Tiere füttern?",
    "Wer hat schon mal in einem fremden Auto eingeschlafen?",
    "Wer würde am ehesten beim Joggen jemandem unwissentlich hinterherrennen?",
    "Wer hat schon mal aus einer Spaßlaune heraus den falschen Bus genommen?",
    "Wer würde am ehesten betrunken einem Fremden seine Lebensgeschichte erzählen?",
    "Wer hat schon mal einen Sprung in eine Pfütze gewagt – im Anzug?",
    "Wer würde am ehesten beim Date mitten in der Stadt einen Strafzettel kassieren?",
    "Wer hat schon mal in einem fremden Garten ein Tier befreit/eingefangen?",
    "Wer würde am ehesten beim Wandern auf einen Baum klettern?",
    "Wer hat schon mal einen Sport ausprobiert, ohne zu wissen, wie er funktioniert?",
    "Wer würde am ehesten beim Fußballspielen mit dem Schiedsrichter streiten?",
    "Wer hat schon mal aus Übermut Klingelmännchen gespielt – nach dem 16. Lebensjahr?",
    "Wer würde am ehesten beim Festival in einen falschen Backstage-Bereich gehen?",
    "Wer hat schon mal Mitten in der Nacht eine Brücke betreten, ohne den Grund zu wissen?",
    "Wer würde am ehesten beim ersten Date ein Trinkspiel vorschlagen?",
    "Wer hat schon mal ein Café besucht und ohne Bestellung lange dort gesessen?",
    "Wer würde am ehesten beim Picknick einen Hund anderer Leute füttern?",
    "Wer hat schon mal beim Camping zwei Zelte aufgebaut und im falschen geschlafen?",
    "Wer würde am ehesten beim Konzert mitgrölen, obwohl er den Song nicht kennt?",
    "Wer hat schon mal in einer fremden Stadt verlaufen und um Hilfe gefragt?",
    "Wer würde am ehesten betrunken einen TikTok-Tanz aufnehmen und hochladen?",
    "Wer hat schon mal seinen Schlüssel im Auto vergessen, mit Motor laufend?",
    "Wer würde am ehesten beim Marathon den ersten Hügel als Wand erleben?",
    "Wer hat schon mal in einem öffentlichen Ort Liegestütze gemacht – auf Wette?",
    "Wer würde am ehesten in einer Disco komplett alleine tanzen?",
    "Wer hat schon mal ein Stadt-Wanderung in High Heels gemacht?",
    "Wer würde am ehesten beim Klettern aus Übermut die Schwierigkeitsstufe erhöhen?",
    "Wer hat schon mal in einer Bahn falsche Auskünfte gegeben – aus Spaß?",
    "Wer würde am ehesten in einem Hochzeitssaal in fremde Tische einladen?",
    "Wer hat schon mal eine Wette angenommen, in der nichts zu gewinnen war?",
    "Wer würde am ehesten beim ersten Date eine Spontan-Bus-Tour vorschlagen?",
    "Wer hat schon mal eine Tasse Kaffee in der Hand verschüttet und so getan, als wäre nichts passiert?",
    "Wer würde am ehesten beim Wandern aus Übermut barfuß weiterlaufen?",
    "Wer hat schon mal in einem Park geschlafen?",
    "Wer würde am ehesten Mitten in einer Vorstellung lachen, wenn niemand lacht?",
    "Wer hat schon mal ein Selfie an einem Aussichtsturm gemacht – und ist fast gefallen?",
    "Wer würde am ehesten beim Skifahren versehentlich auf eine Schwarze Piste raten?",
    "Wer hat schon mal ein Postpaket angenommen, das gar nicht für ihn war?",
    "Wer würde am ehesten als Erster bei einem Spinning-Kurs durchhalten – durch reinen Bock?",
    "Wer hat schon mal in einem fremden Land mit einem schlechten Akzent bestellt?",
    "Wer würde am ehesten beim Camping eine Geistergeschichte erzählen, um andere zu erschrecken?",
    "Wer hat schon mal in einer Bibliothek lautstark gelacht?",
    "Wer würde am ehesten ein Bier öffnen, ohne Flaschenöffner?",
    "Wer hat schon mal eine fremde Person umarmt, weil er sie verwechselt hat?",
    "Wer würde am ehesten beim Picknick die Ameisen mitfüttern?",
    "Wer hat schon mal Tanzschuhe getragen, ohne zu wissen, wie man tanzt?",
    "Wer würde am ehesten beim Date plötzlich ein 30-minütiges Solo-Konzert geben?",
    "Wer hat schon mal beim Wandern eine Höhle erkundet?",
    "Wer würde am ehesten beim Friseur 'überrasch mich' sagen?",
    "Wer hat schon mal mitten am Tag eine Hängematte aufgehängt – an einem Ort, wo's nicht erlaubt war?",
    "Wer würde am ehesten beim Buffet alles probieren, auch die Sachen, die er nicht kennt?",
    "Wer hat schon mal mit dem Rad mitten durch eine Fußgängerzone gerast?",
    "Wer würde am ehesten in einer Bar mit dem Kellner befreundet werden?",
    "Wer hat schon mal beim Tauchen einen Fisch umarmt?",
    "Wer würde am ehesten beim Joggen einem Hund die Leine abkaufen wollen?",
    "Wer hat schon mal ein fremdes Picknick gecrasht?",
    "Wer würde am ehesten beim Skiurlaub als Erster auf die Piste, ohne Frühstück?",
    "Wer hat schon mal beim Camping einen Topf voller Nudeln umgekippt?",
    "Wer würde am ehesten beim Wandern alle Schokoriegel im Rucksack vor allen anderen aufessen?",
    "Wer hat schon mal eine Sicherheitsbarriere überquert, um näher dranzukommen?",
    "Wer würde am ehesten beim Karaoke versuchen, einen Song mit Falsett zu singen, der gar keinen hat?",
    "Wer hat schon mal eine spontane Stadtführung für sich selbst gemacht – mit improvisierten Fakten?",
    "Wer würde am ehesten beim Picknick aus Versehen die Wespen anlocken?",
    "Wer hat schon mal mitten in der Nacht in einer Telefonzelle gestanden?",
    "Wer würde am ehesten beim ersten Date eine Karaoke-Bar vorschlagen?",
    "Wer hat schon mal beim Camping einen Schuh verloren – und nicht gefunden?",
    "Wer würde am ehesten beim Wandern einen Stein als Souvenir mitnehmen?",
    "Wer hat schon mal ein E-Scooter im Strömungs-Modus gerade noch gestoppt?",
    "Wer würde am ehesten beim Wandern einen Schmetterling lange anstarren?",
    "Wer hat schon mal in einer Disco Schuhe getauscht – aus Spaß?",
    "Wer würde am ehesten beim Sport-Event als Maskottchen verkleidet auftauchen?",
    "Wer hat schon mal eine Party-Bühne gestürmt, ohne dafür eingeladen zu sein?",
    "Wer würde am ehesten beim Wandern Klatschmohn pflücken, obwohl es verboten ist?",
    "Wer hat schon mal mitten am Tag einen Fluss überquert, ohne Brücke?",
    "Wer würde am ehesten beim Camping um 3 Uhr nachts Gitarre spielen?",
    "Wer hat schon mal eine Wand erklommen, weil die Treppe zu langweilig war?",
    "Wer würde am ehesten beim Skifahren eine Skischule ohne Erfahrung leiten?",
    "Wer hat schon mal in einer Schlange den Plan gemacht, jemand anders nach vorn zu bitten?",
    "Wer würde am ehesten beim Date in einer öffentlichen Bibliothek schlafen?",
    "Wer hat schon mal einen Tanzlehrer dazu gebracht, ihn rauszuwerfen?",
    "Wer würde am ehesten in einer Bar 20 Minuten lang mit dem Barkeeper philosophieren?",
    "Wer hat schon mal eine spontane Party im eigenen Hausflur veranstaltet?",
    "Wer würde am ehesten beim Konzert die Bühne stürmen, weil der Song zu gut ist?",
    "Wer hat schon mal eine Mondscheinwanderung versucht – ohne Lampe?",
    "Wer würde am ehesten beim Picknick die Spinne als Haustier behalten wollen?",
    "Wer hat schon mal in der Disco aus Versehen die Hymne der Mannschaft des Gegners gesungen?",
    "Wer würde am ehesten beim Wandern eine Trompete einpacken?",
    "Wer hat schon mal mitten in der Nacht eine Autobahn-Raststätte erkundet?",
    "Wer würde am ehesten beim Festival aus Versehen das Backstage-Bier trinken?",
    "Wer hat schon mal jemandem die Treppe hinaufgeholfen, der es gar nicht wollte?",
    "Wer würde am ehesten beim Joggen eine Tankstelle stürmen, um Cola zu kaufen?",
    "Wer hat schon mal beim Camping mit einem Igel geredet?",
    "Wer würde am ehesten beim ersten Date eine Geisterbahn vorschlagen?",
    "Wer hat schon mal mitten am Tag eine ganze Pizza alleine bestellt – und gegessen?",
    "Wer würde am ehesten beim Wandern eine ganze Familie überholen und sich anschließend an die Spitze setzen?",
    "Wer hat schon mal ein Bungalow-Dorf nachts erkundet?",
    "Wer würde am ehesten beim Marathon Schokoriegel statt Energy-Riegel essen?",
    "Wer hat schon mal beim Skifahren rückwärts den Hügel runter?",
    "Wer würde am ehesten beim Camping ein Survival-Workshop abhalten?",
    "Wer hat schon mal eine Party verlassen, ohne sich zu verabschieden?",
    "Wer würde am ehesten in einer Disco vier Drinks in der Hand balancieren?",
    "Wer hat schon mal mitten am Tag eine ganze Stange Brot abgekauft – nur weil's so duftete?",
    "Wer würde am ehesten beim Wandern den Wanderführer überholen?",
    "Wer hat schon mal eine spontane Bauchtanzeinlage in der Küche gemacht?",
    "Wer würde am ehesten beim Camping nachts einen Geist sehen wollen?",
    "Wer hat schon mal eine fremde Hochzeit ungeladen besucht?",
    "Wer würde am ehesten beim Date plötzlich ein Lied auf der Straße anstimmen?",
    "Wer hat schon mal ein Schwein in der Bar gestreichelt?",
    "Wer würde am ehesten beim Wandern in einem Bach planschen?",
    "Wer hat schon mal ein Festival komplett alleine besucht?",
    "Wer würde am ehesten beim Bungee-Jumping fragen, ob's umsonst nochmal geht?",
    "Wer hat schon mal mitten am Tag eine Konditorei leergegessen?",
    "Wer würde am ehesten beim ersten Date Skydiving vorschlagen?",
    "Wer hat schon mal in einer Cafeteria einen Stuhl umgeworfen, ohne es zu merken?",
    "Wer würde am ehesten beim Wandern einen Wolfsruf nachmachen?",
    "Wer hat schon mal in einer Bar einer/m Fremden geholfen, ein Lied auswendig zu lernen?",
    "Wer würde am ehesten beim Festival in einem Brunnen baden?",
    "Wer hat schon mal eine ganze Nacht durchwandert?",
    "Wer würde am ehesten beim ersten Date einen Spaziergang im Friedhof vorschlagen?",
    "Wer hat schon mal beim Konzert die Verstärker-Boxen umarmt?",
    "Wer würde am ehesten beim Skifahren eine spontane Ski-Disco starten?",
    "Wer hat schon mal beim Wandern aus Versehen einen Bauernhof angesteuert?",
    "Wer würde am ehesten beim Camping ein Lagerfeuer auslassen und stattdessen einen Beamer aufstellen?",
    "Wer hat schon mal beim Picknick eine Wespe gefangen und freigelassen?",
    "Wer würde am ehesten beim Marathon ein Selfie mit dem Maskottchen machen?",
    "Wer hat schon mal eine Bahnsteigschlange zum Lachen gebracht?",
    "Wer würde am ehesten beim Date ein 30-Minuten-Schweige-Spiel vorschlagen?",
    "Wer hat schon mal mitten am Tag ein Eis-Buffet komplett leergeräumt?",
    "Wer würde am ehesten beim Camping ein Stand-Up-Comedy-Set einbauen?",
    "Wer hat schon mal beim Wandern einen Stein umgedreht, um Käfer zu beobachten?",
    "Wer würde am ehesten beim ersten Date eine Schnitzeljagd vorschlagen?",
    "Wer hat schon mal eine Karaoke-Bar so lange genutzt, dass der Wirt geschlafen hat?",
    "Wer würde am ehesten beim Joggen einen Spurt einlegen, wenn er allein ist?",
    "Wer hat schon mal aus Versehen ein WhatsApp-Status mit dem falschen Foto gepostet?",
    "Wer würde am ehesten in einer Disco aus Versehen den DJ unterbrechen?",
    "Wer hat schon mal eine ganze Nacht in einem Zugabteil verbracht?",
    "Wer würde am ehesten beim Wandern eine Drohne fliegen lassen, ohne Genehmigung?",
    "Wer hat schon mal in einer Schlange Mitten in der Nacht 'Ich bin der Erste' geschrien?",
    "Wer würde am ehesten beim Camping einen Survival-Test vortäuschen?",
    "Wer hat schon mal in einer Cafeteria einen Schreibwettbewerb gestartet?",
    "Wer würde am ehesten beim Skifahren auf einem Stuhl die ganze Piste runter?",
    "Wer hat schon mal beim Konzert sein Handy verloren – und gefunden?",
    "Wer würde am ehesten beim Date eine spontane Hochzeit auf Probe vorschlagen?",
    "Wer hat schon mal beim Wandern eine Bergziege als Reittier in Betracht gezogen?",
    "Wer würde am ehesten beim Festival am Klo eine fremde Person beraten?",
    "Wer hat schon mal mitten in der Nacht eine Eisdiele aus dem Schlaf geklingelt?",
    "Wer würde am ehesten beim ersten Date Skifahren ohne Schnee vorschlagen?",
    "Wer hat schon mal in einer Bar das Lied gewechselt, ohne den DJ zu fragen?",
    "Wer würde am ehesten beim Wandern als Erster den Pavillon der nächsten Wandergruppe besetzen?",
    "Wer hat schon mal in einem Park ein Yoga-Set abgehalten – ungewollt mit Publikum?",
    "Wer würde am ehesten beim Konzert mit den Bandmitgliedern ein Selfie ergattern?",
    "Wer hat schon mal eine Spritztour mit dem Fahrrad gemacht, ohne zu wissen, wohin?",
    "Wer würde am ehesten beim Picknick eine fremde Wiese als 'eigenes Reservat' beanspruchen?",
    "Wer hat schon mal in einem fremden Auto die Musik gewechselt?",
    "Wer würde am ehesten beim Date eine Hot-Wing-Challenge vorschlagen?",
    "Wer hat schon mal in einer Bar dem Barkeeper Tipps geben wollen?",
    "Wer würde am ehesten beim Wandern eine Karteikarten-Sammlung von gesichteten Tieren anlegen?",
    "Wer hat schon mal beim Konzert die Strophe von einem ganz anderen Lied gesungen?",
    "Wer würde am ehesten beim Camping nachts ein Höhlen-Echo testen?",
    "Wer hat schon mal beim Wandern aus Versehen einen Maulwurfshügel zertreten?",
    "Wer würde am ehesten beim Festival in einem fremden Backstage-Bereich Tee trinken?",
    "Wer hat schon mal in einem öffentlichen Pool eine Wasserschlacht angefangen?",
  ],
  hotspicy: [
    "Wer hatte schon mal Sex an einem ungewöhnlichen Ort?",
    "Wer würde am ehesten mit einem Ex wieder ins Bett gehen?",
    "Wer war schon mal in einen besten Freund / eine beste Freundin verliebt?",
    "Wer hat schon mal mit zwei Personen am selben Tag was gehabt?",
    "Wer hat hier die wildesten Storys aus dem Schlafzimmer?",
    "Wer würde am ehesten ein Sextoy mit ins Reisegepäck nehmen?",
    "Wer hatte schon mal eine Affäre mit jemandem, der vergeben war?",
    "Wer würde am ehesten einen Dreier vorschlagen?",
    "Wer hat den ungewöhnlichsten Beziehungs-Lebenslauf?",
    "Wer hat schon mal mit jemandem geschlafen, ohne dessen vollen Namen zu kennen?",
    "Wer würde am ehesten ein Date in der eigenen Stadt mit der Bahn auf eine andere Stadt verlegen, nur um eskalieren zu können?",
    "Wer hat hier die schärfste Sprachnachricht-History?",
    "Wer würde am ehesten beim ersten Date zu schnell die Eltern erwähnen?",
    "Wer hat schon mal die Nachbarn beim Sex gehört (oder umgekehrt)?",
    "Wer würde am ehesten ein Foto in der Bar machen, das er später bereut?",
    "Wer hat hier den intensivsten Tinder-Marathon hinter sich?",
    "Wer hatte schon mal Sex im Auto?",
    "Wer würde am ehesten heimlich auf Insta einer/m Ex stalken?",
    "Wer hat schon mal jemanden bei einer Hochzeit angebaggert?",
    "Wer hat hier den weitesten gereisten One-Night-Stand?",
    "Wer würde am ehesten beim Sex aus Versehen den falschen Namen rufen?",
    "Wer hat hier die wildeste Bett-Erinnerung mit Lachflash dazu?",
    "Wer würde am ehesten beim Date sagen 'Ich bin nicht so der Beziehungstyp'?",
    "Wer hat schon mal eine Person im Pärchen-Vibes attraktiv gefunden?",
    "Wer würde am ehesten ein FWB-Setting (Friends with Benefits) anfangen, das eskaliert?",
    "Wer war schon mal in einer 'Komplizierten' Phase, von der niemand etwas wusste?",
    "Wer würde am ehesten ein Date in seine eigene Wohnung einladen, obwohl sie unaufgeräumt ist?",
    "Wer hat hier die meisten roten Flaggen ignoriert, weil's heiß war?",
    "Wer würde am ehesten in einer offenen Beziehung sein und es nicht erzählen?",
    "Wer hat schon mal jemandem geschrieben 'Komm noch vorbei' nach Mitternacht?",
    "Wer würde am ehesten ein 'romantisches' Date in einer Burger-Bude haben?",
    "Wer hat hier den klassischsten Liebes-Glow-Up gehabt (vorher → nachher)?",
    "Wer würde am ehesten heimlich ein 'On & Off' Verhältnis nicht beenden?",
    "Wer hat schon mal eine richtig peinliche Pickup-Line gehört (oder benutzt)?",
    "Wer hat hier am ehesten ein Nudie im Handy versteckt?",
    "Wer würde am ehesten beim Date sofort von Ex-Beziehungen erzählen?",
    "Wer hat schon mal heimlich auf das Handy des Partners geguckt?",
    "Wer würde am ehesten in einer Karaoke-Bar eine Liebes-Ballade widmen?",
    "Wer hat hier den meisten Backup-Plan an Tinder-Profilen?",
    "Wer würde am ehesten mit dem/der Kollegen:in Sex am Schreibtisch haben?",
    "Wer hat schon mal Sex bei laufendem TV gehabt – mit lautem Fernseher?",
    "Wer würde am ehesten beim Date ein Sextoy als 'Werkzeug' im Glas verstecken?",
    "Wer hat schon mal eine Erotik-Story über sich selbst geschrieben?",
    "Wer hat hier den schärfsten Lieblings-Song für Bett-Momente?",
    "Wer würde am ehesten in einer Hotel-Bar einen Fremden ansprechen?",
    "Wer hat schon mal an einem Strand Sex gehabt – mit Folgen?",
    "Wer würde am ehesten in einer Bibliothek heimlich knutschen?",
    "Wer hat hier am ehesten eine Liebes-Notiz vom Ex aufbewahrt?",
    "Wer würde am ehesten beim Date einen Lippenstift-Test verlangen?",
    "Wer hat schon mal beim Dirty-Talk gekichert wie ein Teenager?",
    "Wer hat hier am ehesten ein heimliches BDSM-Interesse?",
    "Wer würde am ehesten beim Sex aus Versehen vom Bett fallen?",
    "Wer hat schon mal beim Sex die Polizei anrufen müssen (lange Story)?",
    "Wer würde am ehesten mit einem/r Crush schreiben, während er/sie in einer Beziehung ist?",
    "Wer hat hier am ehesten eine Schublade voller Liebesbriefe?",
    "Wer würde am ehesten beim Date eine Tarot-Karte mit dem Wort 'Liebe' ziehen wollen?",
    "Wer hat schon mal eine spontane Liebeserklärung gemacht?",
    "Wer würde am ehesten beim Date Tequila Shots vorschlagen?",
    "Wer hat hier die wildeste 'erster Kuss'-Story?",
    "Wer würde am ehesten in einer Sauna jemanden anflirten?",
    "Wer hat schon mal Sex an einem Aussichtspunkt gehabt?",
    "Wer würde am ehesten beim Date in einer Erotik-Buchhandlung shoppen?",
    "Wer hat schon mal in einem Hotelzimmer eine 'Adults-Only'-Bestellung gemacht?",
    "Wer hat hier am ehesten ein heimliches Tagebuch über jemanden geführt?",
    "Wer würde am ehesten beim Date in einer Discothek tanzen, bis der DJ aufgibt?",
    "Wer hat schon mal beim Sex mit dem Hund ans Lachen gekommen?",
    "Wer würde am ehesten heimlich ein Bett auf einem Balkon einrichten?",
    "Wer hat hier am ehesten eine Sammlung von Liebes-Songs nur für eine Person?",
    "Wer würde am ehesten in einer Sauna mit Fremden in ein 'Saunadate' geraten?",
    "Wer hat schon mal beim Date einen Spaziergang im Regen vorgeschlagen?",
    "Wer würde am ehesten beim ersten Date die Hand seines/r Crushs halten – ohne Vorwarnung?",
    "Wer hat hier am ehesten ein Tinder-Date in einen Therapie-Termin verwandelt?",
    "Wer würde am ehesten beim Sex die ganze Bettwäsche zerreißen?",
    "Wer hat schon mal Sex im Zelt gehabt – auf einem Festival?",
    "Wer würde am ehesten in einer Hochzeit zwei Personen gleichzeitig anflirten?",
    "Wer hat hier am ehesten ein Foto von einem Crush als Wallpaper?",
    "Wer würde am ehesten beim Date über vergangene 'Tabu'-Träume reden?",
    "Wer hat schon mal beim Sex die ganze Nacht durchgemacht – ohne Pause?",
    "Wer würde am ehesten in einer Bar Augen-Kontakt-Spiele spielen?",
    "Wer hat hier am ehesten einen 'Crush-Ordner' im Handy?",
    "Wer würde am ehesten beim Sex ein dramatisches Schluchzen einlegen?",
    "Wer hat schon mal in einer Bar zwei Drinks für einen Crush bestellt?",
    "Wer würde am ehesten beim Date in einer Pizzeria flirten – mit dem Pizzabäcker?",
    "Wer hat hier am ehesten ein Geheim-Date-Outfit, das niemand sehen soll?",
    "Wer würde am ehesten beim Sex laute Musik wechseln, weil 'es passt nicht'?",
    "Wer hat schon mal in einem fremden Garten mit jemandem geknutscht?",
    "Wer würde am ehesten beim Date eine Erotikbuch-Lesung vorschlagen?",
    "Wer hat hier am ehesten ein heimliches Insta-Profil nur für ein Crush?",
    "Wer würde am ehesten beim Sex die Nachbarn um Erlaubnis fragen wollen?",
    "Wer hat schon mal beim Date durch ein Tindergespräch mit jemand anderem getextet?",
    "Wer würde am ehesten beim Sex Tee servieren?",
    "Wer hat hier am ehesten eine 'Notfall-Schublade' für romantische Abende?",
    "Wer würde am ehesten in einer Sauna laut über Beziehungen reden?",
    "Wer hat schon mal beim Date über das Kind-Thema gesprochen – beim ersten Treffen?",
    "Wer würde am ehesten beim Sex aus Versehen den Hund wecken?",
    "Wer hat hier am ehesten ein Liebes-Brief an sich selbst geschrieben?",
    "Wer würde am ehesten beim Date ein 'Speed-Dating' für sich selbst veranstalten?",
    "Wer hat schon mal beim Sex Mitten in der Nacht aus Spaß die Lichter eingeschaltet?",
    "Wer würde am ehesten beim ersten Date eine 'Was wäre wenn'-Frage stellen, die zu intim ist?",
    "Wer hat hier am ehesten ein Liebes-Spiel im Schlafzimmer – mit Würfeln?",
    "Wer würde am ehesten beim Sex die Bett-Pose 'Statue' ausprobieren?",
    "Wer hat schon mal mit jemandem geschlafen, der/die ihn/sie eigentlich abgrundtief hasst?",
    "Wer würde am ehesten beim Date eine Liebes-Karaoke vorschlagen?",
    "Wer hat hier am ehesten eine Sammlung an 'Best-of-Tinder-Profilen'?",
    "Wer würde am ehesten beim Sex einen Snack-Break einlegen?",
    "Wer hat schon mal beim Date eine Trennung gemimt – aus Spaß?",
    "Wer würde am ehesten beim Sex mitten in der Nacht eine Pizza bestellen?",
    "Wer hat hier am ehesten den ehrgeizigsten Crush, den niemand kennt?",
    "Wer würde am ehesten beim Date eine Liebes-Wett-Wand vorschlagen?",
    "Wer hat schon mal beim Sex einen Stuhl zerstört?",
    "Wer würde am ehesten beim ersten Date über Schamgrenzen lachen?",
    "Wer hat hier am ehesten heimlich ein 'Spotify-für-Sex'-Playlist?",
    "Wer würde am ehesten beim Sex schief liegen, weil das Bett zu wackelig ist?",
    "Wer hat schon mal beim Date Augen für eine ganz andere Person geübt?",
    "Wer würde am ehesten beim Sex eine Bettdecke verlieren?",
    "Wer hat hier am ehesten am wenigsten Sex – und am meisten Theorie dazu?",
    "Wer würde am ehesten beim Date ein 'Was würdest du heute Nacht tun'-Spiel anfangen?",
    "Wer hat schon mal beim Sex die Wand verschönert?",
    "Wer würde am ehesten beim Date in einer Disco zu eng tanzen?",
    "Wer hat hier am ehesten eine heimliche Liste an 'wer-mich-für-eine-Nacht-bekommen-würde'?",
    "Wer würde am ehesten beim Sex die Glühbirne durchbrennen lassen?",
    "Wer hat schon mal beim Date einen Liebes-Kettenbrief verschickt?",
    "Wer würde am ehesten beim Sex eine Tee-Pause vorschlagen?",
    "Wer hat hier am ehesten eine heimliche Vorliebe für Hotelzimmer-Roleplay?",
    "Wer würde am ehesten beim Date eine spontane Tattoo-Stelle vorschlagen?",
    "Wer hat schon mal beim Sex aus Versehen 'Mama' gerufen?",
    "Wer würde am ehesten in einer Karaoke-Bar einen heißen Tanz aufführen?",
    "Wer hat hier am ehesten ein Liebes-Geheimnis, das nur eine Person kennt?",
    "Wer würde am ehesten beim Sex einen romantischen Brief aus der Schublade ziehen?",
    "Wer hat schon mal beim Date Mitten am Tag im Park gekuschelt?",
    "Wer würde am ehesten beim Sex einen Massage-Workshop einlegen?",
    "Wer hat hier am ehesten eine heimliche 'Liebes-Vision' für die nächsten 10 Jahre?",
    "Wer würde am ehesten beim ersten Date die Frage 'Bist du in mich verliebt?' stellen?",
    "Wer hat schon mal beim Sex Mitten in der Nacht eine Reise gebucht?",
    "Wer würde am ehesten beim Date in einer Galerie über Aktbilder kichern?",
    "Wer hat hier am ehesten eine heimliche Affäre, die seit Monaten läuft?",
    "Wer würde am ehesten beim Sex die ganze Nacht über die Lampe an lassen?",
    "Wer hat schon mal beim Date eine spontane Strip-Show im Auto?",
    "Wer würde am ehesten beim Sex die ganze Bettwäsche aus dem Fenster werfen?",
    "Wer hat hier am ehesten einen 'romantischen Notfall-Plan B'?",
    "Wer würde am ehesten beim Date eine Hauswand zur Slideshow nutzen?",
    "Wer hat schon mal beim Sex aus Versehen ein Tier in die Wohnung gelassen?",
    "Wer würde am ehesten beim ersten Date 'Wollen wir Kinder?' fragen – im Spaß?",
    "Wer hat hier am ehesten eine heimliche Bett-Routine, die nur funktioniert mit der richtigen Musik?",
    "Wer würde am ehesten beim Sex auf Hochdeutsch wechseln, um schicker zu klingen?",
    "Wer hat schon mal beim Date ein anderes Date heimlich verschoben?",
    "Wer würde am ehesten beim Sex ein 'Romantik-Picknick' im Bett aufbauen?",
    "Wer hat hier am ehesten eine Liste an Tabus, die er/sie irgendwann mal brechen möchte?",
    "Wer würde am ehesten beim Date in einer Kirche flüstern, um den Atem zu spüren?",
    "Wer hat schon mal beim Sex eine Lampe umgestoßen – und ein neues Möbelstück gekauft?",
    "Wer würde am ehesten beim Date mit dem Bus heim, statt mit dem Taxi, nur um länger zu reden?",
    "Wer hat hier am ehesten ein 'Heimlich-verliebt'-Erlebnis, das niemand kennt?",
    "Wer würde am ehesten beim Sex aus Versehen die Lieblings-Vase umstoßen?",
    "Wer hat schon mal beim Date in einer Buchhandlung 'die Liebes-Ecke' alleine durchstöbert?",
    "Wer würde am ehesten beim Sex einen 'Pausensong' brauchen?",
    "Wer hat hier am ehesten eine Lieblings-Sextoy-Empfehlung an Freunde weitergegeben?",
    "Wer würde am ehesten beim ersten Date plötzlich heiraten wollen?",
    "Wer hat schon mal beim Sex einen Spiegel aus dem Schrank geholt?",
    "Wer würde am ehesten beim Date in einem Park ein heimliches Selfie machen?",
    "Wer hat hier am ehesten 'Spotify-Wrapped'-Songs, die alle peinlich sind?",
    "Wer würde am ehesten beim Sex einen 'Eis-am-Stiel'-Pause-Vorschlag machen?",
    "Wer hat schon mal beim Date in einer 'Was-wenn'-Diskussion fast schon eine Beziehung 'reserviert'?",
    "Wer würde am ehesten beim Sex einen Geheim-Spiegel-Reflektion testen?",
    "Wer hat hier am ehesten eine 'Liebes-Bingo'-Karte erstellt?",
    "Wer würde am ehesten beim Sex Mitten in der Nacht den Kühlschrank durchwühlen?",
    "Wer hat schon mal beim Date eine spontane Liebes-Sketch im Klo gemacht?",
    "Wer würde am ehesten beim Sex einen 'Liebes-Pet'-Namen wechseln?",
    "Wer hat hier am ehesten eine geheime Lieblings-Bett-Position, die er/sie nicht zugibt?",
    "Wer würde am ehesten beim Date eine Liebes-Erkenntnis 'einfach so' aussprechen?",
    "Wer hat schon mal beim Sex einen Geistesblitz für einen Roman bekommen?",
    "Wer würde am ehesten beim ersten Date ein 'Wenn-wir-ehrlich-sind'-Spiel anfangen?",
    "Wer hat hier am ehesten eine 'Liebes-Erinnerung'-Sammlung in der Schreibtischschublade?",
    "Wer würde am ehesten beim Sex 30 Minuten lang über Politik reden – aus Spaß?",
    "Wer hat schon mal beim Date eine Liebes-Notiz auf die Serviette gekritzelt?",
    "Wer würde am ehesten beim Sex ein 'Wir-machen-mal-Pause'-Schild aufhängen?",
    "Wer hat hier am ehesten eine 'Heimlich-Verliebt'-Person, die niemals davon erfahren wird?",
    "Wer würde am ehesten beim ersten Date 'Ich glaube, das ist Liebe' sagen?",
    "Wer hat schon mal beim Sex einen Lachflash, der die ganze Stimmung gekillt hat?",
    "Wer würde am ehesten beim Date eine 'Was-würden-deine-Eltern-sagen'-Diskussion provozieren?",
    "Wer hat hier am ehesten heimlich ein Foto vom Date als Hintergrund?",
    "Wer würde am ehesten beim Sex spontan an einen Roadtrip denken?",
    "Wer hat schon mal beim Date in einer Bar mit jemandem getanzt, ohne ein Wort zu wechseln?",
    "Wer würde am ehesten beim Sex eine 'Nase-an-Nase'-Pause machen wollen?",
    "Wer hat hier am ehesten ein Liebes-Erlebnis, das er/sie nie wieder erleben möchte?",
    "Wer würde am ehesten beim Date eine Liebes-Geste machen, die niemand versteht?",
    "Wer hat schon mal beim Sex die Bettdecke fast verbrannt?",
    "Wer würde am ehesten beim ersten Date Mitten in einer Diskussion einen Kuss versuchen?",
    "Wer hat hier am ehesten eine 'Liebes-Playlist' für jeden Wochentag?",
    "Wer würde am ehesten beim Sex die ganze Wohnung mit Kerzen voll machen?",
    "Wer hat schon mal beim Date 'Ich hatte einen Traum von dir' gesagt?",
    "Wer würde am ehesten beim Sex eine 'Liebes-Selfie-Pause' einlegen?",
    "Wer hat hier am ehesten heimlich eine Liebeskunde-Liste in der Notiz-App?",
    "Wer würde am ehesten beim ersten Date ein Tarot-Kartenlegung 'für uns' bezahlen?",
    "Wer hat schon mal beim Sex an Mitten in der Nacht Mitternachts-Snacks geträumt?",
    "Wer würde am ehesten beim Date über Geheim-Crushes aus der Schulzeit reden?",
    "Wer hat hier am ehesten eine 'Heimlich-Verheiratet'-Fantasie?",
    "Wer würde am ehesten beim Sex Mitten in der Nacht eine 'Pause-Diskussion' anfangen?",
    "Wer hat schon mal beim Date eine 'romantische' Krise zu früh provoziert?",
  ],
};

export interface Fragen99Card {
  text: string;
  cat: Fragen99Category;
  index: number;
}

export function pickQuestion(
  cats: Fragen99Category[],
  used: Set<string>,
  index: number,
): Fragen99Card | null {
  const pool: { text: string; cat: Fragen99Category }[] = [];
  for (const c of cats) for (const t of FRAGEN99_QUESTIONS[c]) pool.push({ text: t, cat: c });
  if (pool.length === 0) return null;
  const fresh = pool.filter((p) => !used.has(p.text));
  const arr = fresh.length > 0 ? fresh : pool;
  const pick = arr[Math.floor(Math.random() * arr.length)];
  return { text: pick.text, cat: pick.cat, index };
}

// Eskalierende Schluck-Mechanik:
// Je weiter die Runde fortschreitet, desto mehr Schlücke kassiert die gewählte Person.
//   Frage  1 – 20 → 1 Schluck
//   Frage 21 – 40 → 2 Schlücke
//   Frage 41 – 60 → 3 Schlücke
//   Frage 61 – 80 → 4 Schlücke
//   Frage 81 – 99 → 5 Schlücke
export function sipsForQuestion(index: number): number {
  if (index <= 20) return 1;
  if (index <= 40) return 2;
  if (index <= 60) return 3;
  if (index <= 80) return 4;
  return 5;
}

// Tier metadata for UI hints
export interface SipsTier {
  level: number;
  label: string;
  min: number;
  max: number;
  sips: number;
}

export const SIPS_TIERS: SipsTier[] = [
  { level: 1, label: "Warm-up", min: 1, max: 20, sips: 1 },
  { level: 2, label: "Auf Betriebstemperatur", min: 21, max: 40, sips: 2 },
  { level: 3, label: "Es wird heiß", min: 41, max: 60, sips: 3 },
  { level: 4, label: "Endspurt", min: 61, max: 80, sips: 4 },
  { level: 5, label: "Wahnsinns-Modus", min: 81, max: 99, sips: 5 },
];

export function getTierForQuestion(index: number): SipsTier {
  return SIPS_TIERS.find((t) => index >= t.min && index <= t.max) ?? SIPS_TIERS[0];
}
