// Begriffe für Imposter-Spiel: [Wort, Tipp]
// Tipps sind bewusst einzelne, allgemeine Wörter – sie deuten die Richtung an, verraten aber nichts.
export type ImposterCategory =
  | "einfach"
  | "trends"
  | "spicy"
  | "clash"
  | "fortnite"
  | "marken"
  | "spiele"
  | "filme"
  | "fussball"
  | "helden"
  | "stars";

export const IMPOSTER_CATEGORIES: { id: ImposterCategory; label: string; emoji: string }[] = [
  { id: "einfach", label: "Einfache Wörter", emoji: "💡" },
  { id: "trends", label: "Trends", emoji: "📈" },
  { id: "spicy", label: "Spicy (18+)", emoji: "🌶️" },
  { id: "clash", label: "Clash Royale", emoji: "👑" },
  { id: "fortnite", label: "Fortnite", emoji: "🎮" },
  { id: "marken", label: "Marken", emoji: "🏷️" },
  { id: "spiele", label: "Gesellschaftsspiele", emoji: "🎲" },
  { id: "filme", label: "Filme & Serien", emoji: "🎬" },
  { id: "fussball", label: "Fußball", emoji: "⚽" },
  { id: "helden", label: "Superhelden", emoji: "🦸" },
  { id: "stars", label: "Stars & Promis", emoji: "⭐" },
];

type WP = [string, string]; // [word, hint]

export const IMPOSTER_WORDS: Record<ImposterCategory, WP[]> = {
  einfach: [
    ["Pizza", "Essen"], ["Hund", "Tier"], ["Auto", "Fahrzeug"],
    ["Apfel", "Obst"], ["Sonne", "Himmel"], ["Stuhl", "Möbel"],
    ["Buch", "Lesen"], ["Schule", "Gebäude"], ["Strand", "Urlaub"],
    ["Regen", "Wetter"], ["Kaffee", "Getränk"], ["Bett", "Möbel"],
    ["Fenster", "Haus"], ["Schuh", "Kleidung"], ["Brille", "Sicht"],
    ["Telefon", "Technik"], ["Gitarre", "Instrument"], ["Zahnbürste", "Bad"],
    ["Wasser", "Getränk"], ["Brot", "Essen"], ["Fahrrad", "Fahrzeug"],
    ["Banane", "Obst"], ["Mond", "Himmel"], ["Tasse", "Geschirr"],
    ["Baum", "Natur"], ["Berg", "Natur"], ["Hose", "Kleidung"],
    ["Spiegel", "Glas"], ["Schlüssel", "Metall"], ["Computer", "Technik"],
    ["Kühlschrank", "Küche"], ["Schokolade", "Süß"], ["Wolke", "Himmel"],
    ["Schnee", "Wetter"], ["Tisch", "Möbel"], ["Lampe", "Licht"],
    ["Uhr", "Zeit"], ["Schere", "Werkzeug"], ["Hammer", "Werkzeug"],
    ["Sand", "Strand"], ["Fisch", "Tier"], ["Vogel", "Tier"],
    ["Katze", "Tier"], ["Maus", "Tier"], ["Pferd", "Tier"],
    ["Schiff", "Fahrzeug"], ["Flugzeug", "Fahrzeug"], ["Zug", "Fahrzeug"],
    ["Rucksack", "Tasche"], ["Bleistift", "Schreiben"],
    ["Eis", "Süß"], ["Salat", "Essen"],
  ],
  trends: [
    ["TikTok", "App"], ["Skibidi Toilet", "Meme"], ["Mango Mango Mango", "Song"],
    ["Stanley Cup", "Trinken"], ["Labubu", "Spielzeug"], ["BookTok", "Bücher"],
    ["Sleepy Girl Mocktail", "Drink"], ["Roman Empire", "Geschichte"],
    ["Quiet Luxury", "Mode"], ["Mob Wife", "Mode"], ["Hawk Tuah", "Meme"],
    ["Brat Summer", "Musik"], ["Demure", "Verhalten"],
    ["Gigi Hadid Pasta", "Rezept"], ["Dubai Schokolade", "Süß"],
    ["Birkin Bag", "Luxus"], ["Old Money", "Stil"],
    ["Coastal Grandma", "Stil"], ["Girl Dinner", "Essen"],
    ["Rizz", "Slang"], ["Sigma", "Slang"], ["Cap", "Slang"],
    ["NPC", "Slang"], ["Delulu", "Slang"], ["Slay", "Slang"],
    ["Ohio", "Meme"], ["Gyatt", "Slang"], ["Mid", "Slang"],
    ["Lock In", "Slang"], ["Bussin", "Slang"], ["Bruh", "Slang"],
    ["BeReal", "App"], ["Threads", "App"], ["Discord", "App"],
    ["Twitch", "Plattform"], ["ChatGPT", "KI"],
    ["Spotify Wrapped", "Musik"], ["Tradwife", "Lifestyle"],
    ["Wes Anderson Style", "Film"], ["Goblin Mode", "Lifestyle"],
    ["Cozy Gaming", "Gaming"], ["ASMR", "Sound"],
    ["Influencer", "Beruf"], ["Twerken", "Tanz"], ["Y2K", "Mode"],
    ["Cottagecore", "Stil"], ["Streetwear", "Mode"],
    ["Vintage", "Mode"], ["Vinted", "App"], ["Vinyl", "Musik"],
  ],
  spicy: [
    ["Missionarsstellung", "Stellung"], ["Reiterstellung", "Stellung"],
    ["Doggy Style", "Stellung"], ["Löffelchen", "Stellung"], ["69", "Stellung"],
    ["Reverse Cowgirl", "Stellung"], ["Brücke", "Stellung"],
    ["Stehend an der Wand", "Stellung"], ["Lotussitz", "Stellung"],
    ["Quickie", "Sex"], ["Vorspiel", "Sex"], ["Dirty Talk", "Sex"],
    ["Striptease", "Show"], ["Lapdance", "Show"],
    ["Augenbinde", "Toy"], ["Handschellen", "Toy"],
    ["Federkitzler", "Toy"], ["Massageöl", "Toy"], ["Safeword", "Sex"],
    ["Rollenspiel", "Sex"], ["Dreier", "Sex"],
    ["Swingerclub", "Ort"], ["FKK-Strand", "Ort"],
    ["OnlyFans", "Plattform"], ["Dessous", "Kleidung"],
    ["Vibrator", "Toy"], ["Kondom", "Schutz"],
    ["Tantra", "Sex"], ["Kamasutra", "Buch"],
    ["Schäferstündchen", "Sex"], ["Affäre", "Beziehung"],
    ["One Night Stand", "Beziehung"], ["Friends with Benefits", "Beziehung"],
    ["Tinder Match", "Dating"], ["Knutschfleck", "Kuss"],
    ["Zungenkuss", "Kuss"], ["Liebesbiss", "Kuss"],
    ["Pole Dance", "Tanz"], ["Hotelzimmer", "Ort"],
    ["Aphrodisiakum", "Lust"],
  ],
  clash: [
    ["Hog Rider", "Truppe"], ["Goblin", "Truppe"],
    ["Wizard", "Truppe"], ["Mini Pekka", "Truppe"],
    ["Pekka", "Truppe"], ["Drachen", "Truppe"],
    ["Riese", "Truppe"], ["Skelette", "Truppe"],
    ["Eiswurm", "Truppe"], ["Eisgolem", "Truppe"],
    ["Eismagier", "Truppe"], ["Inferno-Turm", "Gebäude"],
    ["Tesla", "Gebäude"], ["Kanone", "Gebäude"],
    ["Mörser", "Gebäude"], ["X-Bow", "Gebäude"],
    ["Bombenwerfer", "Truppe"], ["Walküre", "Truppe"],
    ["Prinz", "Truppe"], ["Dunkler Prinz", "Truppe"],
    ["Bandit", "Truppe"], ["Bandit-Anführer", "Truppe"],
    ["Mega Knight", "Truppe"], ["Ram Rider", "Truppe"],
    ["Royale Riese", "Truppe"], ["Royale Champion", "Champion"],
    ["Goldener Ritter", "Champion"], ["Skelett-König", "Champion"],
    ["Archer Queen", "Champion"], ["Mighty Miner", "Champion"],
    ["Hexe", "Truppe"], ["Nachthexe", "Truppe"],
    ["Mutter-Hexe", "Truppe"], ["Babydrache", "Truppe"],
    ["Lavahund", "Truppe"], ["Ballon", "Truppe"],
    ["Bomber", "Truppe"], ["Speerwerfer", "Truppe"],
    ["Bogenschützen", "Truppe"], ["Magierdrache", "Truppe"],
    ["Sparky", "Truppe"], ["Elektro-Magier", "Truppe"],
    ["Elixiergolem", "Truppe"], ["Truhe", "Belohnung"],
    ["Pokal", "Rang"], ["Gold", "Währung"],
    ["Edelsteine", "Währung"], ["Klan", "Gruppe"],
    ["Arena", "Spielmodus"], ["Pfeil", "Zauber"],
    ["Feuerball", "Zauber"], ["Blitz", "Zauber"],
    ["Tornado", "Zauber"],
  ],
  fortnite: [
    ["Battle Bus", "Start"], ["Tilted Towers", "POI"],
    ["Pleasant Park", "POI"], ["Retail Row", "POI"],
    ["Salty Springs", "POI"], ["Loot Lake", "POI"],
    ["Dusty Depot", "POI"], ["Greasy Grove", "POI"],
    ["Lazy Lagoon", "POI"], ["Sweaty Sands", "POI"],
    ["Sturmkreis", "Mechanik"], ["V-Bucks", "Währung"],
    ["Battle Pass", "Belohnung"], ["Skin", "Outfit"],
    ["Emote", "Tanz"], ["Default Dance", "Tanz"],
    ["Floss", "Tanz"], ["Take the L", "Tanz"],
    ["Schubkarre", "Fahrzeug"], ["Quadcrasher", "Fahrzeug"],
    ["Auto", "Fahrzeug"], ["Boot", "Fahrzeug"],
    ["Spitzhacke", "Werkzeug"], ["Bauen", "Mechanik"],
    ["Zero Build", "Modus"], ["Solo", "Modus"],
    ["Duo", "Modus"], ["Squad", "Modus"],
    ["LTM", "Modus"], ["Battle Royale", "Modus"],
    ["Save the World", "Modus"], ["Llama", "Loot"],
    ["Truhe", "Loot"], ["Supply Drop", "Loot"],
    ["Med Kit", "Heilung"], ["Mini Shield", "Heilung"],
    ["Big Shield", "Heilung"], ["Chug Jug", "Heilung"],
    ["Slurp Juice", "Heilung"], ["Pumpgun", "Waffe"],
    ["SMG", "Waffe"], ["Sniper", "Waffe"], ["Scar", "Waffe"],
    ["Boogie Bomb", "Item"], ["Granate", "Waffe"],
    ["Trap", "Falle"], ["Ramp", "Bau"],
    ["John Wick Skin", "Skin"], ["Peely", "Skin"],
    ["Drift", "Skin"], ["Raven", "Skin"],
    ["Marshmello", "Event"], ["Travis Scott", "Event"],
    ["Eminem", "Event"],
  ],
  marken: [
    ["Nike", "Sport"], ["Adidas", "Sport"], ["Puma", "Sport"],
    ["Apple", "Tech"], ["Samsung", "Tech"], ["Sony", "Tech"],
    ["Microsoft", "Tech"], ["Google", "Tech"],
    ["Amazon", "Onlineshop"], ["Coca-Cola", "Getränk"],
    ["Pepsi", "Getränk"], ["Red Bull", "Getränk"],
    ["McDonald's", "Fastfood"], ["Burger King", "Fastfood"],
    ["KFC", "Fastfood"], ["Subway", "Fastfood"],
    ["Starbucks", "Kaffee"], ["IKEA", "Möbel"],
    ["H&M", "Mode"], ["Zara", "Mode"],
    ["Gucci", "Luxus"], ["Louis Vuitton", "Luxus"],
    ["Prada", "Luxus"], ["Chanel", "Luxus"],
    ["Hermès", "Luxus"], ["Rolex", "Luxus"],
    ["BMW", "Auto"], ["Mercedes", "Auto"],
    ["Audi", "Auto"], ["Porsche", "Auto"],
    ["Volkswagen", "Auto"], ["Tesla", "Auto"],
    ["Ferrari", "Auto"], ["Lamborghini", "Auto"],
    ["Toyota", "Auto"], ["Ford", "Auto"],
    ["Lego", "Spielzeug"], ["Disney", "Unterhaltung"],
    ["Netflix", "Streaming"], ["Spotify", "Musik"],
    ["YouTube", "Plattform"], ["Instagram", "App"],
    ["Facebook", "App"], ["WhatsApp", "App"],
    ["Telegram", "App"], ["Snapchat", "App"],
    ["Ferrero", "Süß"], ["Milka", "Süß"],
    ["Haribo", "Süß"], ["Lindt", "Süß"],
    ["Nivea", "Kosmetik"], ["L'Oréal", "Kosmetik"],
  ],
  spiele: [
    ["Monopoly", "Brettspiel"], ["Risiko", "Brettspiel"],
    ["Siedler von Catan", "Brettspiel"], ["Carcassonne", "Brettspiel"],
    ["Mensch ärgere dich nicht", "Brettspiel"], ["Cluedo", "Brettspiel"],
    ["Scrabble", "Brettspiel"], ["Schach", "Brettspiel"],
    ["Dame", "Brettspiel"], ["Mühle", "Brettspiel"],
    ["Backgammon", "Brettspiel"], ["Skip-Bo", "Kartenspiel"],
    ["UNO", "Kartenspiel"], ["Phase 10", "Kartenspiel"],
    ["Wizard", "Kartenspiel"], ["Mau Mau", "Kartenspiel"],
    ["Skat", "Kartenspiel"], ["Doppelkopf", "Kartenspiel"],
    ["Schafkopf", "Kartenspiel"], ["Romé", "Kartenspiel"],
    ["Poker", "Kartenspiel"], ["Black Jack", "Kartenspiel"],
    ["Activity", "Partyspiel"], ["Tabu", "Partyspiel"],
    ["Pantomime", "Partyspiel"], ["Codenames", "Partyspiel"],
    ["Werwolf", "Partyspiel"], ["Mafia", "Partyspiel"],
    ["Wahrheit oder Pflicht", "Partyspiel"], ["Flaschendrehen", "Partyspiel"],
    ["Twister", "Partyspiel"], ["Jenga", "Geschicklichkeit"],
    ["Dr. Bibber", "Geschicklichkeit"], ["Mikado", "Geschicklichkeit"],
    ["Memory", "Brettspiel"], ["Halli Galli", "Kartenspiel"],
    ["Set", "Kartenspiel"], ["Dixit", "Kartenspiel"],
    ["Just One", "Partyspiel"], ["6 nimmt!", "Kartenspiel"],
    ["Wer wird Millionär", "Quiz"], ["Trivial Pursuit", "Quiz"],
    ["Stadt Land Fluss", "Stiftspiel"], ["Tetris", "Videospiel"],
    ["Sudoku", "Knobeln"], ["Käsekästchen", "Stiftspiel"],
    ["Schiffe versenken", "Stiftspiel"], ["Galgenmännchen", "Stiftspiel"],
    ["Vier gewinnt", "Brettspiel"], ["Solitär", "Kartenspiel"],
    ["Rummikub", "Brettspiel"], ["Kniffel", "Würfelspiel"],
  ],
  filme: [
    ["Titanic", "Film"], ["Avatar", "Film"],
    ["Star Wars", "Reihe"], ["Harry Potter", "Reihe"],
    ["Herr der Ringe", "Reihe"], ["Der Pate", "Film"],
    ["Pulp Fiction", "Film"], ["Inception", "Film"],
    ["Interstellar", "Film"], ["Matrix", "Film"],
    ["Fluch der Karibik", "Reihe"], ["Jurassic Park", "Film"],
    ["Forrest Gump", "Film"], ["Joker", "Film"],
    ["Django Unchained", "Film"], ["Breaking Bad", "Serie"],
    ["Game of Thrones", "Serie"], ["Stranger Things", "Serie"],
    ["The Walking Dead", "Serie"], ["Friends", "Sitcom"],
    ["How I Met Your Mother", "Sitcom"], ["Big Bang Theory", "Sitcom"],
    ["Squid Game", "Serie"], ["Money Heist", "Serie"],
    ["Dark", "Serie"], ["Vikings", "Serie"],
    ["Peaky Blinders", "Serie"], ["The Office", "Sitcom"],
    ["Suits", "Serie"], ["Lucifer", "Serie"],
    ["Sherlock", "Serie"], ["Wednesday", "Serie"],
    ["Mando", "Serie"], ["House of Cards", "Serie"],
    ["Narcos", "Serie"], ["The Crown", "Serie"],
    ["Avengers", "Comicfilm"], ["Iron Man", "Comicfilm"],
    ["Spider-Man", "Comicfilm"], ["Batman", "Comicfilm"],
    ["Deadpool", "Comicfilm"], ["Frozen", "Animation"],
    ["König der Löwen", "Animation"], ["Findet Nemo", "Animation"],
    ["Shrek", "Animation"], ["Toy Story", "Animation"],
    ["Ice Age", "Animation"], ["Minions", "Animation"],
    ["Madagaskar", "Animation"], ["Kung Fu Panda", "Animation"],
    ["Cars", "Animation"], ["Ratatouille", "Animation"],
  ],
  fussball: [
    ["Bayern München", "Verein"], ["Borussia Dortmund", "Verein"],
    ["RB Leipzig", "Verein"], ["Schalke 04", "Verein"],
    ["Werder Bremen", "Verein"], ["Hamburger SV", "Verein"],
    ["FC Köln", "Verein"], ["Bayer Leverkusen", "Verein"],
    ["Eintracht Frankfurt", "Verein"], ["Real Madrid", "Verein"],
    ["FC Barcelona", "Verein"], ["Atlético Madrid", "Verein"],
    ["Manchester United", "Verein"], ["Manchester City", "Verein"],
    ["FC Liverpool", "Verein"], ["FC Chelsea", "Verein"],
    ["FC Arsenal", "Verein"], ["Tottenham", "Verein"],
    ["Juventus Turin", "Verein"], ["AC Mailand", "Verein"],
    ["Inter Mailand", "Verein"], ["AS Rom", "Verein"],
    ["SSC Neapel", "Verein"], ["Paris Saint-Germain", "Verein"],
    ["Ajax Amsterdam", "Verein"], ["Lionel Messi", "Spieler"],
    ["Cristiano Ronaldo", "Spieler"], ["Erling Haaland", "Spieler"],
    ["Kylian Mbappé", "Spieler"], ["Neymar", "Spieler"],
    ["Harry Kane", "Spieler"], ["Jamal Musiala", "Spieler"],
    ["Florian Wirtz", "Spieler"], ["Manuel Neuer", "Torwart"],
    ["Toni Kroos", "Spieler"], ["Thomas Müller", "Spieler"],
    ["Joshua Kimmich", "Spieler"], ["Marc-André ter Stegen", "Torwart"],
    ["Vinícius Júnior", "Spieler"], ["Jude Bellingham", "Spieler"],
    ["Pep Guardiola", "Trainer"], ["Jürgen Klopp", "Trainer"],
    ["Carlo Ancelotti", "Trainer"], ["Hansi Flick", "Trainer"],
    ["WM-Finale", "Turnier"], ["Champions League", "Turnier"],
    ["Europa League", "Turnier"], ["DFB-Pokal", "Turnier"],
    ["Elfmeter", "Regel"], ["Freistoß", "Regel"],
    ["Eckball", "Regel"], ["Abseits", "Regel"],
    ["VAR", "Regel"], ["Rote Karte", "Regel"],
  ],
  helden: [
    ["Spider-Man", "Marvel"], ["Iron Man", "Marvel"],
    ["Captain America", "Marvel"], ["Thor", "Marvel"],
    ["Hulk", "Marvel"], ["Black Widow", "Marvel"],
    ["Hawkeye", "Marvel"], ["Doctor Strange", "Marvel"],
    ["Black Panther", "Marvel"], ["Wolverine", "Marvel"],
    ["Deadpool", "Marvel"], ["Star-Lord", "Marvel"],
    ["Gamora", "Marvel"], ["Groot", "Marvel"],
    ["Rocket Raccoon", "Marvel"], ["Scarlet Witch", "Marvel"],
    ["Vision", "Marvel"], ["Ant-Man", "Marvel"],
    ["Wasp", "Marvel"], ["Captain Marvel", "Marvel"],
    ["Loki", "Marvel"], ["Daredevil", "Marvel"],
    ["Moon Knight", "Marvel"], ["Punisher", "Marvel"],
    ["Batman", "DC"], ["Superman", "DC"],
    ["Wonder Woman", "DC"], ["The Flash", "DC"],
    ["Aquaman", "DC"], ["Green Lantern", "DC"],
    ["Cyborg", "DC"], ["Robin", "DC"],
    ["Nightwing", "DC"], ["Batgirl", "DC"],
    ["Joker", "Schurke"], ["Harley Quinn", "Schurke"],
    ["Catwoman", "Schurke"], ["Pinguin", "Schurke"],
    ["Riddler", "Schurke"], ["Lex Luthor", "Schurke"],
    ["Thanos", "Schurke"], ["Magneto", "Schurke"],
    ["Green Goblin", "Schurke"], ["Doc Ock", "Schurke"],
    ["Venom", "Schurke"], ["Carnage", "Schurke"],
    ["Storm", "Marvel"], ["Cyclops", "Marvel"],
    ["Jean Grey", "Marvel"], ["Professor X", "Marvel"],
    ["Quicksilver", "Marvel"], ["Falcon", "Marvel"],
    ["Winter Soldier", "Marvel"],
  ],
  stars: [
    ["Taylor Swift", "Sängerin"], ["Beyoncé", "Sängerin"],
    ["Rihanna", "Sängerin"], ["Adele", "Sängerin"],
    ["Lady Gaga", "Sängerin"], ["Ariana Grande", "Sängerin"],
    ["Billie Eilish", "Sängerin"], ["Dua Lipa", "Sängerin"],
    ["Selena Gomez", "Sängerin"], ["Miley Cyrus", "Sängerin"],
    ["Drake", "Rapper"], ["Kanye West", "Rapper"],
    ["Eminem", "Rapper"], ["Travis Scott", "Rapper"],
    ["Post Malone", "Rapper"], ["Ed Sheeran", "Sänger"],
    ["Justin Bieber", "Sänger"], ["The Weeknd", "Sänger"],
    ["Bruno Mars", "Sänger"], ["Harry Styles", "Sänger"],
    ["Leonardo DiCaprio", "Schauspieler"], ["Brad Pitt", "Schauspieler"],
    ["Tom Cruise", "Schauspieler"], ["Tom Hanks", "Schauspieler"],
    ["Will Smith", "Schauspieler"], ["Johnny Depp", "Schauspieler"],
    ["Robert Downey Jr.", "Schauspieler"], ["Chris Hemsworth", "Schauspieler"],
    ["Chris Evans", "Schauspieler"], ["Ryan Reynolds", "Schauspieler"],
    ["Ryan Gosling", "Schauspieler"], ["Keanu Reeves", "Schauspieler"],
    ["Margot Robbie", "Schauspielerin"], ["Scarlett Johansson", "Schauspielerin"],
    ["Jennifer Aniston", "Schauspielerin"], ["Angelina Jolie", "Schauspielerin"],
    ["Emma Stone", "Schauspielerin"], ["Emma Watson", "Schauspielerin"],
    ["Zendaya", "Schauspielerin"], ["Kim Kardashian", "Promi"],
    ["Kylie Jenner", "Promi"], ["Heidi Klum", "Model"],
    ["Bibi Claßen", "Influencer"], ["MontanaBlack", "Streamer"],
    ["Knossi", "Streamer"], ["Trymacs", "Streamer"],
    ["Apoplexy", "Streamer"], ["Elon Musk", "Unternehmer"],
    ["Mark Zuckerberg", "Unternehmer"], ["Jeff Bezos", "Unternehmer"],
    ["Bill Gates", "Unternehmer"], ["Donald Trump", "Politiker"],
    ["Barack Obama", "Politiker"],
  ],
};

export function pickImposterWord(cats: ImposterCategory[]): { word: string; hint: string } {
  const allowed = cats.length > 0 ? cats : (Object.keys(IMPOSTER_WORDS) as ImposterCategory[]);
  const pool = allowed.flatMap((c) => IMPOSTER_WORDS[c]);
  const pick = pool[Math.floor(Math.random() * pool.length)];
  return { word: pick[0], hint: pick[1] };
}
